# generated by datamodel-codegen:
#   canonical source: schemas/contracts.schema.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)


class SchemaVersion(RootModel[Literal['1.0.0']]):
    root: Literal['1.0.0']


class SemVer(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern='^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$'
        ),
    ]


class Identifier(RootModel[StrictStr]):
    root: Annotated[
        StrictStr, Field(pattern='^[a-z][a-z0-9]{1,11}_[0-9A-HJKMNP-TV-Z]{26}$')
    ]


class RunId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^run_[0-9A-HJKMNP-TV-Z]{26}$')]


class TargetId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^tgt_[0-9A-HJKMNP-TV-Z]{26}$')]


class Hash(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^sha256:[0-9a-f]{64}$')]


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime


class Uri(RootModel[AnyUrl]):
    root: AnyUrl


class RelativePath(RootModel[StrictStr]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        StrictStr,
        Field(
            max_length=512,
            min_length=1,
            pattern='^(?![/\\\\])(?!.*(?:^|[/\\\\])\\.\\.(?:[/\\\\]|$))(?!.*[\\u0000-\\u001f]).+$',
        ),
    ]


class Confidence(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]


class TrustClass(
    RootModel[
        Literal[
            'deterministic_tool',
            'runtime_observation',
            'verified_source',
            'target_source_claim',
            'curated_external',
            'human_asserted',
            'adjudicated',
            'model_observation',
            'model_assumption',
        ]
    ]
):
    root: Literal[
        'deterministic_tool',
        'runtime_observation',
        'verified_source',
        'target_source_claim',
        'curated_external',
        'human_asserted',
        'adjudicated',
        'model_observation',
        'model_assumption',
    ]


class EvidenceGrade(
    RootModel[Literal['lead', 'supported', 'observed', 'defect_pinned', 'validated']]
):
    root: Literal['lead', 'supported', 'observed', 'defect_pinned', 'validated']


class GraphNamespace(RootModel[Literal['target', 'global', 'learning']]):
    root: Literal['target', 'global', 'learning']


class VersionedContractId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=128,
            min_length=1,
            pattern='^[a-z][a-z0-9-]*@(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$',
        ),
    ]


class GlobalStreamIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    namespace: Literal['global']
    stream_id: Identifier
    corpus_id: Identifier
    release_id: Identifier
    ontology_version: SemVer
    manifest_hash: Hash


class LearningStreamIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    namespace: Literal['learning']
    stream_id: Identifier
    learning_id: Identifier
    origin_run_id: RunId | None
    origin_target_key: Hash | None


class HypothesisOrigin(
    RootModel[
        Literal[
            'model_novel',
            'global_graph',
            'contradiction',
            'tool',
            'coverage',
            'specialist',
        ]
    ]
):
    root: Literal[
        'model_novel', 'global_graph', 'contradiction', 'tool', 'coverage', 'specialist'
    ]


class HypothesisStatus(
    RootModel[
        Literal[
            'lead',
            'supported',
            'poc_worthy',
            'observed',
            'defect_pinned',
            'validated',
            'falsified',
            'needs_missing_fact',
            'needs_reformulation',
            'parked',
            'duplicate_known_issue',
            'reported',
        ]
    ]
):
    root: Literal[
        'lead',
        'supported',
        'poc_worthy',
        'observed',
        'defect_pinned',
        'validated',
        'falsified',
        'needs_missing_fact',
        'needs_reformulation',
        'parked',
        'duplicate_known_issue',
        'reported',
    ]


class EvidenceCeiling(
    RootModel[Literal['lead', 'supported', 'observed', 'defect_pinned']]
):
    root: Literal['lead', 'supported', 'observed', 'defect_pinned']


class TargetIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_id: TargetId
    source_tree_hash: Hash
    scope_id: Identifier
    commit: Annotated[StrictStr | None, Field(pattern='^[0-9a-f]{40}$')] = None


class StringMapEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        StrictStr,
        Field(max_length=128, min_length=1, pattern='^[A-Za-z_][A-Za-z0-9_.-]*$'),
    ]
    value: Annotated[StrictStr, Field(max_length=2048)]


class TypedProperty(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        StrictStr, Field(max_length=128, min_length=1, pattern='^[a-z][a-z0-9_.-]*$')
    ]
    value_type: Literal['string', 'integer', 'number', 'boolean', 'identifier', 'hash']
    value: StrictStr | StrictInt | StrictFloat | StrictBool | None


class ReferenceList(RootModel[list[Identifier]]):
    root: Annotated[list[Identifier], Field(max_length=256)]


class HashList(RootModel[list[Hash]]):
    root: Annotated[list[Hash], Field(max_length=256)]


class AyranWriterAndActorIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'human', 'model', 'service', 'tool', 'specialist', 'gate', 'router', 'importer'
    ]
    id: Annotated[
        StrictStr, Field(max_length=128, min_length=1, pattern='^[a-z][a-z0-9_.:-]*$')
    ]
    version: SemVer
    independence_group: Annotated[
        StrictStr | None, Field(max_length=128, pattern='^[a-z][a-z0-9_.:-]*$')
    ] = None


class AyranProvenanceRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provenance_id: Identifier
    source_uri: Uri
    source_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    raw_hash: Hash
    retrieved_at: Timestamp
    license_or_terms: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    extraction_locator: Annotated[StrictStr | None, Field(max_length=512)] = None
    parser_version: SemVer | None = None
    transformation_lineage: Annotated[list[Hash], Field(max_length=64)]


class AyranIntegrityEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: Literal['sha256']
    canonicalization: Literal['rfc8785']
    content_hash: Hash
    excluded_fields: Annotated[
        list[Literal['integrity.content_hash', 'event_hash']],
        Field(max_length=2, min_length=1),
    ]


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_id: Annotated[
        StrictStr,
        Field(max_length=128, min_length=1, pattern='^[a-z][a-z0-9-]*@1\\.0\\.0$'),
    ]
    object_id: Identifier
    content_hash: Hash


class GraphEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    event_id: Identifier
    seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    graph: GraphNamespace
    aggregate_id: Identifier
    aggregate_version: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    event_type: Annotated[
        StrictStr,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
        ),
    ]
    actor: AyranWriterAndActorIdentity
    operation_id: Identifier
    run_id: RunId
    target_identity: TargetIdentity
    created_at: Timestamp
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope
    config_hash: Hash
    source_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    idempotency_key: Annotated[
        StrictStr,
        Field(max_length=256, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]*$'),
    ]
    payload: Payload
    previous_event_hash: Hash | None
    event_hash: Hash


class GraphNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    node_id: Identifier
    created_at: Timestamp
    run_id: RunId | None
    namespace: GraphNamespace
    node_type: Annotated[
        StrictStr, Field(max_length=96, min_length=1, pattern='^[A-Z][A-Za-z0-9]*$')
    ]
    revision: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    status: Literal['active', 'stale_pending_revalidation', 'tombstoned']
    properties: Annotated[list[TypedProperty], Field(max_length=256)]
    trust_class: TrustClass
    confidence: Confidence
    evidence_grade: EvidenceGrade
    evidence_refs: ReferenceList
    source_locator: Annotated[StrictStr, Field(max_length=512, min_length=1)]
    valid_from_event: Identifier
    valid_to_event: Identifier | None = None
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class GraphEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    edge_id: Identifier
    created_at: Timestamp
    run_id: RunId | None
    namespace: GraphNamespace
    edge_type: Literal[
        'CALLS',
        'READS',
        'WRITES',
        'CONTROLS',
        'TRANSFERS',
        'DEPENDS_ON',
        'MUST_PRESERVE',
        'ASSUMES',
        'CONTRADICTS',
        'VIOLATES',
        'REQUIRES',
        'ENABLES',
        'APPLICABLE_TO',
        'SIMILAR_TO',
        'VARIANT_OF',
        'EVIDENCED_BY',
        'REFUTED_BY',
        'REPRODUCED_BY',
        'KILLED_BY_FIX',
        'DETECTED_BY',
        'DUPLICATES',
        'KNOWN_ISSUE_OF',
        'LEARNED_FROM',
    ]
    source_id: Identifier
    target_id: Identifier
    revision: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    status: Literal['active', 'stale_pending_revalidation', 'tombstoned']
    properties: Annotated[list[TypedProperty], Field(max_length=128)]
    trust_class: TrustClass
    confidence: Confidence
    evidence_grade: EvidenceGrade
    evidence_refs: ReferenceList
    source_locator: Annotated[StrictStr, Field(max_length=512, min_length=1)]
    valid_from_event: Identifier
    valid_to_event: Identifier | None = None
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Identity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['target', 'corpus']
    id: Identifier
    version_hash: Hash


class GraphAssertion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    assertion_id: Identifier
    created_at: Timestamp
    run_id: RunId | None
    namespace: GraphNamespace
    subject_id: Identifier
    predicate: Annotated[
        StrictStr, Field(max_length=128, min_length=1, pattern='^[a-z][a-z0-9_.-]*$')
    ]
    object_kind: Literal['identifier', 'string', 'integer', 'number', 'boolean', 'hash']
    object_value: StrictStr | StrictInt | StrictFloat | StrictBool
    writer: AyranWriterAndActorIdentity
    written_at: Timestamp
    source_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    identity: Identity
    trust_class: TrustClass
    confidence: Confidence
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    artifact_refs: HashList
    valid_from_event: Identifier
    valid_to_event: Identifier | None = None
    supersedes: ReferenceList
    contradiction_group: Identifier | None
    integrity: AyranIntegrityEnvelope


class Transition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['snapshot', 'retraction', 'tombstone']
    reason: Annotated[StrictStr | None, Field(max_length=2048)]
    supersedes: ReferenceList


class Body(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_id: VersionedContractId
    object_id: Identifier
    content_hash: Hash
    value: dict[str, Any]
    transition: Transition


class ExpectedRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregate_id: Identifier
    revision: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class Issue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[StrictStr, Field(pattern='^[A-Z][A-Z0-9_]*$')]
    message: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    segment: Annotated[StrictStr | None, Field(pattern='^[0-9]{6}\\.jsonl$')]
    line: Annotated[StrictInt | None, Field(ge=1)]
    retryable: StrictBool


class Snapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    as_of_seq: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    event_hash: Hash | None
    projection_schema_version: SemVer
    migration_version: Annotated[StrictInt, Field(ge=1)]


class Language(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class Chain(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class Framework(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class Supports(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    languages: Annotated[list[Language], Field(max_length=32)]
    chains: Annotated[list[Chain], Field(max_length=32)]
    frameworks: Annotated[list[Framework], Field(max_length=32)]
    phases: Annotated[
        list[
            Literal[
                'scope',
                'mapping',
                'discovery',
                'validation',
                'falsification',
                'dedup',
                'reporting',
            ]
        ],
        Field(min_length=1),
    ]


class Trigger(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_.-]*$')]


class QuestionsAnsweredItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class Prerequisite(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class ArgvItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256)]


class Detect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: Annotated[list[ArgvItem], Field(max_length=32, min_length=1)]
    parser: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_.-]*$')]


class HealthCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_.-]*$')]


class InstallPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed: StrictBool
    approval: Literal['always', 'never']
    checksum_required: StrictBool
    global_mutation_allowed: Literal[False]


class ArgvTemplateItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256)]


class Invocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv_template: Annotated[list[ArgvTemplateItem], Field(max_length=64, min_length=1)]
    shell: Literal[False]


class Resources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpu: Annotated[StrictInt, Field(ge=1, le=64)]
    memory_mib: Annotated[StrictInt, Field(ge=64, le=131072)]
    disk_mib: Annotated[StrictInt, Field(ge=0, le=1048576)]
    network: Literal['none', 'approved-api', 'rpc-allowlist', 'approved-source-fetch']


class SecretAliase(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^[A-Z][A-Z0-9_]{2,63}_REF$')]


class Retry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transient: Annotated[StrictInt, Field(ge=0, le=3)]
    deterministic: Literal[0]


class Cooldown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consecutive_failures: Annotated[StrictInt, Field(ge=1, le=10)]
    scope: Literal['action', 'run', 'environment']


class Fallback(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_.-]*$')]


class Cleanup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    receipt_owned_only: Literal[True]
    preserve_artifacts: StrictBool
    remove_external_dependencies: Literal[False]


class CapabilityManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    capability_id: Identifier
    created_at: Timestamp
    version: SemVer
    kind: Literal[
        'executable_adapter',
        'http_adapter',
        'skill',
        'specialist',
        'deterministic_service',
    ]
    ownership: Literal['ayran', 'external_detect_only']
    supports: Supports
    triggers: Annotated[list[Trigger], Field(max_length=64, min_length=1)]
    questions_answered: Annotated[
        list[QuestionsAnsweredItem], Field(max_length=64, min_length=1)
    ]
    prerequisites: Annotated[list[Prerequisite], Field(max_length=64)]
    detect: Detect
    health_check: HealthCheck
    install_policy: InstallPolicy
    input_schema: Annotated[
        StrictStr, Field(pattern='^[A-Za-z][A-Za-z0-9]*@1\\.0\\.0$')
    ]
    output_schema: Annotated[
        StrictStr, Field(pattern='^[A-Za-z][A-Za-z0-9]*@1\\.0\\.0$')
    ]
    invocation: Invocation
    evidence_ceiling: EvidenceCeiling
    resources: Resources
    sandbox_profile: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    secret_aliases: Annotated[list[SecretAliase], Field(max_length=16)]
    timeout_seconds: Annotated[StrictInt, Field(ge=1, le=86400)]
    retry: Retry
    cooldown: Cooldown
    failure_taxonomy: Annotated[
        list[
            Literal[
                'prerequisite',
                'compile',
                'test',
                'timeout',
                'oom',
                'network',
                'rpc',
                'parser_drift',
                'policy',
                'internal',
            ]
        ],
        Field(min_length=1),
    ]
    fallbacks: Annotated[list[Fallback], Field(max_length=16)]
    cleanup: Cleanup
    owner: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    last_verified: date
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Deployment(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern='^0x[0-9a-fA-F]{40}$')]


class Chain1(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]


class ForkBlock(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class Budgets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wall_minutes: Annotated[StrictInt, Field(ge=1, le=10080)]
    token_units: Annotated[StrictInt, Field(ge=1, le=100000000)]
    tool_seconds: Annotated[StrictInt, Field(ge=0, le=604800)]
    disk_mib: Annotated[StrictInt, Field(ge=1, le=1048576)]


class ApprovalRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_class: Literal[
        'install_tool',
        'add_endpoint',
        'expand_scope',
        'external_upload',
        'submission',
        'signing',
        'spending',
        'transaction_broadcast',
    ]
    approval: Literal['explicit-human']


class Authorization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_by: AyranWriterAndActorIdentity
    approved_scope_hash: Hash
    approved_at: Timestamp


class Action(
    RootModel[
        Literal[
            'read_source',
            'read_spec',
            'graph_read',
            'graph_write',
            'compile_local',
            'test_local',
            'fuzz_local',
            'read_only_rpc',
            'approved_api_query',
            'render_local_report',
        ]
    ]
):
    root: Literal[
        'read_source',
        'read_spec',
        'graph_read',
        'graph_write',
        'compile_local',
        'test_local',
        'fuzz_local',
        'read_only_rpc',
        'approved_api_query',
        'render_local_report',
    ]


class Rule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule_id: Identifier
    effect: Literal['allow', 'deny']
    action: Action
    resource: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class AttackPathItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class Precondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    status: Literal['unknown', 'source_claim', 'observed', 'refuted']
    attacker_can_create: StrictBool | None


class ImpactPremise(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal[
        'asset_theft',
        'unbacked_claim',
        'debt_escape',
        'governance_takeover',
        'permanent_lock',
        'mev_extraction',
        'integrity_violation',
        'availability',
    ]
    description: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    upper_bound: Annotated[StrictStr | None, Field(max_length=128)]


class Prior(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['model', 'historical', 'tool', 'human']
    confidence: Confidence


class RequiredFalsifier(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class Budget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_units: Annotated[StrictInt, Field(ge=0, le=10000000)]
    tool_seconds: Annotated[StrictInt, Field(ge=0, le=86400)]
    wall_minutes: Annotated[StrictInt, Field(ge=1, le=1440)]


class TransitionHistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: Annotated[HypothesisStatus | None, Field(alias='from')]
    to: HypothesisStatus
    event_id: Identifier
    actor: AyranWriterAndActorIdentity
    at: Timestamp
    evidence_ids: ReferenceList


class Hypothesis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    hypothesis_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    origin: HypothesisOrigin
    claim: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    invariant_ids: ReferenceList
    attack_path: Annotated[list[AttackPathItem], Field(max_length=64, min_length=1)]
    target_entities: ReferenceList
    preconditions: Annotated[list[Precondition], Field(max_length=64, min_length=1)]
    impact_premise: ImpactPremise
    priors: Annotated[list[Prior], Field(max_length=32)]
    novelty: Literal['unknown', 'no_known_precedent', 'variant', 'known_mechanism']
    required_falsifiers: Annotated[
        list[RequiredFalsifier], Field(max_length=32, min_length=1)
    ]
    budget: Budget
    parent_ids: ReferenceList
    duplicate_candidate_ids: ReferenceList
    status: HypothesisStatus
    evidence_grade: EvidenceGrade
    trust_class: TrustClass
    confidence: Confidence
    transition_history: Annotated[
        list[TransitionHistoryItem], Field(max_length=128, min_length=1)
    ]
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Redaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    secret_scan_passed: StrictBool
    redacted: StrictBool


class ArgvItem1(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512)]


class Reproduction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: Annotated[list[ArgvItem1], Field(max_length=128, min_length=1)]
    working_root: RelativePath
    environment_hash: Hash
    expected_result_hash: Hash


class EvidenceArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    evidence_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    artifact_hash: Hash
    size_bytes: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    mime_type: Annotated[
        StrictStr, Field(pattern='^[a-z0-9][a-z0-9.+-]*/[a-z0-9][a-z0-9.+-]*$')
    ]
    producer: AyranWriterAndActorIdentity
    producer_version: SemVer
    input_hashes: HashList
    config_hash: Hash
    fork_identity_hash: Hash | None
    raw_locator: RelativePath
    normalized_locator: RelativePath | None
    evidence_grade: EvidenceGrade
    trust_class: TrustClass
    confidence: Confidence
    supports: ReferenceList
    refutes: ReferenceList
    redaction: Redaction
    reproduction: Reproduction
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Limits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpu: Annotated[StrictInt, Field(ge=1, le=64)]
    memory_mib: Annotated[StrictInt, Field(ge=64, le=131072)]
    disk_mib: Annotated[StrictInt, Field(ge=0, le=1048576)]
    wall_seconds: Annotated[StrictInt, Field(ge=1, le=86400)]
    network: Literal['none', 'approved-api', 'rpc-allowlist', 'approved-source-fetch']


class ToolRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    tool_run_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    capability_id: Identifier
    capability_version: SemVer
    adapter_version: SemVer
    tool_name: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    tool_version: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    argv: Annotated[list[ArgvItem1], Field(max_length=128, min_length=1)]
    environment: Annotated[list[StringMapEntry], Field(max_length=64)]
    working_root: RelativePath
    input_hashes: HashList
    seed: Annotated[StrictInt | None, Field(ge=0, le=9007199254740991)]
    fork_identity_hash: Hash | None
    limits: Limits
    started_at: Timestamp
    ended_at: Timestamp
    exit_code: Annotated[StrictInt | None, Field(ge=-2147483648, le=2147483647)]
    signal: Annotated[StrictStr | None, Field(max_length=64)]
    stdout_hash: Hash
    stderr_hash: Hash
    artifact_refs: HashList
    parse_status: Literal['parsed', 'partial', 'failed', 'parser_drift']
    parser_version: SemVer
    normalized_evidence_ids: ReferenceList
    evidence_ceiling: EvidenceCeiling
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Gap(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class Blocker(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class UntriedDimension(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class CoverageCell(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    coverage_cell_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    dimension: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    target_refs: ReferenceList
    invariant_ids: ReferenceList
    entry_point_ids: ReferenceList
    attempted_origins: Annotated[list[HypothesisOrigin], Field(max_length=6)]
    attempted_tools: ReferenceList
    depth: Literal['inventory', 'reviewed', 'tested', 'falsified', 'blocked']
    achieved_evidence_grade: EvidenceGrade
    status: Literal['open', 'examined', 'blocked', 'accepted_residual_risk']
    examined_result: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    gaps: Annotated[list[Gap], Field(max_length=64)]
    blockers: Annotated[list[Blocker], Field(max_length=64)]
    untried_dimensions: Annotated[list[UntriedDimension], Field(max_length=64)]
    updated_at: Timestamp
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class DAVerdict(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    verdict_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    gate: Literal['A', 'B']
    decision: Literal['advance', 'revise', 'reject', 'duplicate', 'insufficient']
    resulting_hypothesis_status: HypothesisStatus
    hypothesis_id: Identifier
    evidence_ids: ReferenceList
    falsification_attempts: Annotated[
        list[FalsificationAttempt], Field(max_length=64, min_length=1)
    ]
    causal_chain: Annotated[list[CausalChainItem], Field(max_length=64, min_length=1)]
    dissent: Annotated[list[DissentItem], Field(max_length=32)]
    confidence: Confidence
    deterministic_rule_version: SemVer
    reviewer: AyranWriterAndActorIdentity
    independent_from: ReferenceList
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class AffectedCodeItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class Precondition1(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class Assumption(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class Impact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['loss', 'theft', 'lock', 'governance', 'availability', 'integrity']
    equation: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    lower_bound: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    upper_bound: Annotated[StrictStr | None, Field(max_length=128)]
    assumptions: Annotated[list[Assumption], Field(max_length=64)]


class FindingCandidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    finding_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    status: Literal['candidate']
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    root_cause: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    violated_invariant: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    affected_code: Annotated[list[AffectedCodeItem], Field(max_length=64, min_length=1)]
    attacker_model: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    preconditions: Annotated[list[Precondition1], Field(max_length=64, min_length=1)]
    impact: Impact
    evidence_ids: ReferenceList
    trust_class: TrustClass
    confidence: Confidence
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Impact1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['loss', 'theft', 'lock', 'governance', 'availability', 'integrity']
    equation: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    lower_bound: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    upper_bound: Annotated[StrictStr | None, Field(max_length=128)]
    assumptions: Annotated[list[Assumption], Field(max_length=64)]


class DuplicateDisposition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['unique', 'variant', 'duplicate_known_issue']
    comparison: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    source_refs: Annotated[list[Uri], Field(max_length=32)]


class Severity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: Literal['informational', 'low', 'medium', 'high', 'critical']
    policy_id: Identifier
    rule_citation: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class UncertaintyItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class Mitigation(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=2048, min_length=1)]


class ValidatedFinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    finding_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    status: Literal['validated']
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    root_cause: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    violated_invariant: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    affected_code: Annotated[list[AffectedCodeItem], Field(max_length=64, min_length=1)]
    attacker_model: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    preconditions: Annotated[list[Precondition1], Field(max_length=64, min_length=1)]
    impact: Impact1
    evidence_ids: Annotated[list[Identifier], Field(max_length=256, min_length=1)]
    gate_a_verdict_id: Identifier
    gate_b_verdict_id: Identifier
    reproduction_artifact_id: Identifier
    negative_control_ids: Annotated[
        list[Identifier], Field(max_length=64, min_length=1)
    ]
    defect_fix_evidence_ids: Annotated[
        list[Identifier], Field(max_length=64, min_length=1)
    ]
    scope_manifest_id: Identifier
    duplicate_disposition: DuplicateDisposition
    severity: Severity
    uncertainty: Annotated[list[UncertaintyItem], Field(max_length=64)]
    mitigations: Annotated[list[Mitigation], Field(max_length=64, min_length=1)]
    trust_class: TrustClass
    confidence: Confidence
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Impact2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['loss', 'theft', 'lock', 'governance', 'availability', 'integrity']
    equation: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    lower_bound: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    upper_bound: Annotated[StrictStr | None, Field(max_length=128)]
    assumptions: Annotated[list[Assumption], Field(max_length=64)]


class Base(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    finding_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    root_cause: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    violated_invariant: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    affected_code: Annotated[list[AffectedCodeItem], Field(max_length=64, min_length=1)]
    attacker_model: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    preconditions: Annotated[list[Precondition1], Field(max_length=64, min_length=1)]
    impact: Impact2
    evidence_ids: ReferenceList
    trust_class: TrustClass
    confidence: Confidence
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Rights(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    license_or_terms: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    redistribution_allowed: StrictBool
    reviewed: StrictBool


class QuarantinedLearningOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    learning_outcome_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    promotion_stage: Literal['quarantined']
    result: Literal['accepted', 'rejected', 'duplicate', 'inconclusive', 'unsafe']
    adjudication: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    generalized_candidate: Annotated[StrictStr | None, Field(max_length=4096)]
    source_lineage: HashList
    rights: Rights
    contamination_class: Literal[
        'production', 'development', 'sealed-holdout', 'unknown'
    ]
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class Rights1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    license_or_terms: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    redistribution_allowed: StrictBool
    reviewed: Literal[True]


class HeldOutEvaluation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evaluation_id: Identifier
    passed: StrictBool
    result_hash: Hash
    project_families: Annotated[StrictInt, Field(ge=2, le=1000)]


class EvaluatedLearningOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    learning_outcome_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    promotion_stage: Literal['evaluated']
    result: Literal['accepted', 'rejected', 'duplicate', 'inconclusive', 'unsafe']
    adjudication: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    generalized_candidate: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    source_lineage: Annotated[list[Hash], Field(max_length=256, min_length=1)]
    rights: Rights1
    contamination_class: Literal['production', 'development']
    reviewers: Annotated[
        list[AyranWriterAndActorIdentity], Field(max_length=8, min_length=2)
    ]
    positive_test_ids: Annotated[list[Identifier], Field(max_length=64, min_length=1)]
    hard_negative_test_ids: Annotated[
        list[Identifier], Field(max_length=64, min_length=1)
    ]
    held_out_evaluation: HeldOutEvaluation
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class HeldOutEvaluation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evaluation_id: Identifier
    passed: Literal[True]
    result_hash: Hash
    project_families: Annotated[StrictInt, Field(ge=2, le=1000)]


class ReleasedLearningOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    learning_outcome_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    promotion_stage: Literal['released']
    result: Literal['accepted']
    adjudication: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    generalized_candidate: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    source_lineage: Annotated[list[Hash], Field(max_length=256, min_length=1)]
    rights: Rights1
    contamination_class: Literal['production', 'development']
    reviewers: Annotated[
        list[AyranWriterAndActorIdentity], Field(max_length=8, min_length=2)
    ]
    positive_test_ids: Annotated[list[Identifier], Field(max_length=64, min_length=1)]
    hard_negative_test_ids: Annotated[
        list[Identifier], Field(max_length=64, min_length=1)
    ]
    held_out_evaluation: HeldOutEvaluation1
    release_pointer: Identifier
    rollback_pointer: Identifier
    promotion_approved_by: AyranWriterAndActorIdentity
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class CoreProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class OmittedCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    global_: Annotated[StrictInt, Field(alias='global', ge=0, le=9007199254740991)]
    learning: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classification: Literal[
        'POLICY',
        'DETERMINISTIC_FACT',
        'RUNTIME_OBSERVATION',
        'SOURCE_CLAIM',
        'ASSUMPTION',
        'HYPOTHESIS',
        'HISTORICAL_REFERENCE',
        'COUNTEREVIDENCE',
        'UNTRUSTED_DATA',
    ]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    content: Annotated[StrictStr, Field(max_length=16384, min_length=1)]
    source_ids: ReferenceList


class ContextPack(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    context_pack_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    purpose: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    role: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    graph_cursor: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    query_ids: ReferenceList
    included_object_ids: ReferenceList
    included_evidence_ids: ReferenceList
    excluded_object_ids: ReferenceList
    omitted_counts: OmittedCounts
    token_estimate: Annotated[StrictInt, Field(ge=0, le=1000000)]
    policy_checksum: Hash
    config_checksum: Hash
    based_on_event_hash: Hash
    fresh_until_event: Identifier | None
    knowledge_policy: Literal['target_only', 'knowledge_blind', 'graph_aware']
    sections: Annotated[list[Section], Field(max_length=128, min_length=1)]
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class RouterAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    router_action_id: Identifier
    created_at: Timestamp
    run_id: RunId
    target_identity: TargetIdentity
    triggering_event_ids: Annotated[
        list[Identifier], Field(max_length=64, min_length=1)
    ]
    policy_version: SemVer
    deduplication_key: Annotated[
        StrictStr,
        Field(max_length=256, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]*$'),
    ]
    handler: Handler
    priority: Annotated[StrictInt, Field(ge=0, le=1000)]
    budget_effect: BudgetEffect
    dependencies: ReferenceList
    authorization: Authorization_1
    status: Literal[
        'eligible', 'queued', 'running', 'succeeded', 'failed', 'denied', 'cancelled'
    ]
    context_pack_id: Identifier | None
    owner: AyranWriterAndActorIdentity
    deadline: Timestamp
    stop_condition: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    emitted_operation_ids: ReferenceList
    result_ids: ReferenceList
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class AyranCommonContractDefinitions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    identifier: Identifier
    hash: Hash
    created_at: Timestamp


class TargetStreamIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    namespace: Literal['target']
    stream_id: Identifier
    run_id: RunId
    target_identity: TargetIdentity
    target_key: Hash


class GraphStreamIdentity(
    RootModel[TargetStreamIdentity | GlobalStreamIdentity | LearningStreamIdentity]
):
    root: TargetStreamIdentity | GlobalStreamIdentity | LearningStreamIdentity


class JournalEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    event_id: Identifier
    seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    stream: GraphStreamIdentity
    batch_id: Identifier
    ordinal: Annotated[StrictInt, Field(ge=1, le=10000)]
    aggregate_id: Identifier
    aggregate_version: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    event_type: Annotated[
        StrictStr,
        Field(
            max_length=128,
            min_length=3,
            pattern='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$',
        ),
    ]
    actor: AyranWriterAndActorIdentity
    operation_id: Identifier
    causation_id: Identifier | None
    created_at: Timestamp
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope
    config_hash: Hash
    source_version: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    idempotency_key: Annotated[
        StrictStr,
        Field(max_length=256, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]*$'),
    ]
    body: Body
    previous_event_hash: Hash | None
    event_hash: Hash


class BatchBegin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    hash_domain: Literal['ayran.journal.begin.v1']
    record_type: Literal['batch.begin']
    stream: GraphStreamIdentity
    batch_id: Identifier
    operation_id: Identifier
    causation_id: Identifier | None
    idempotency_key: Annotated[
        StrictStr,
        Field(max_length=256, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]*$'),
    ]
    request_hash: Hash
    expected_revisions: Annotated[list[ExpectedRevision], Field(max_length=10000)]
    first_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    event_count: Annotated[StrictInt, Field(ge=1, le=10000)]
    previous_event_hash: Hash | None
    previous_commit_hash: Hash | None
    created_at: Timestamp


class BatchEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    record_type: Literal['batch.event']
    event: JournalEvent


class BatchCommit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    hash_domain: Literal['ayran.journal.commit.v1']
    record_type: Literal['batch.commit']
    stream: GraphStreamIdentity
    batch_id: Identifier
    event_count: Annotated[StrictInt, Field(ge=1, le=10000)]
    first_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    last_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    first_event_hash: Hash
    last_event_hash: Hash
    begin_hash: Hash
    members_hash: Hash
    previous_commit_hash: Hash | None
    committed_at: Timestamp
    commit_hash: Hash


class GraphAcknowledgement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    stream: GraphStreamIdentity
    batch_id: Identifier
    operation_id: Identifier
    idempotency_key: Annotated[
        StrictStr,
        Field(max_length=256, min_length=1, pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]*$'),
    ]
    request_hash: Hash
    first_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    last_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    event_ids: Annotated[list[Identifier], Field(max_length=10000, min_length=1)]
    event_hashes: Annotated[list[Hash], Field(max_length=10000, min_length=1)]
    commit_hash: Hash
    projection_cursor: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    projection_event_hash: Hash
    idempotent_replay: StrictBool


class GraphCheckpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    checkpoint_id: Identifier
    created_at: Timestamp
    stream: GraphStreamIdentity
    journal_cursor: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    journal_event_hash: Hash | None
    journal_commit_hash: Hash | None
    projection_schema_version: SemVer
    migration_version: Annotated[StrictInt, Field(ge=1, le=1000000)]
    target_hash: Hash | None
    config_hash: Hash | None
    source_hash: Hash | None
    tool_hash: Hash | None
    artifact_manifest_hash: Hash | None
    outbox_digest: Hash
    projection_digest: Hash
    integrity: AyranIntegrityEnvelope


class SegmentManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    journal_format_version: Literal[1]
    segment_id: Identifier
    segment_name: Annotated[StrictStr, Field(pattern='^[0-9]{6}\\.jsonl$')]
    stream: GraphStreamIdentity
    first_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    last_seq: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    first_event_hash: Hash
    last_event_hash: Hash
    first_commit_hash: Hash
    last_commit_hash: Hash
    previous_manifest_hash: Hash | None
    event_count: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    batch_count: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    byte_size: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    file_hash: Hash
    merkle_root: Hash
    backup_state: Literal['pending', 'verified']
    created_at: Timestamp
    closed_at: Timestamp
    integrity: AyranIntegrityEnvelope


class GraphIntegrityReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    report_id: Identifier
    created_at: Timestamp
    operation: Literal['verify', 'replay', 'rebuild', 'doctor']
    stream: GraphStreamIdentity
    status: Literal['ok', 'recovered', 'corrupt', 'incompatible']
    journal_cursor: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    projection_cursor: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    last_event_hash: Hash | None
    last_commit_hash: Hash | None
    verified_segments: Annotated[StrictInt, Field(ge=0)]
    verified_batches: Annotated[StrictInt, Field(ge=0)]
    verified_events: Annotated[StrictInt, Field(ge=0)]
    issues: Annotated[list[Issue], Field(max_length=10000)]
    recovered_suffix_hash: Hash | None
    query_digest: Hash | None
    integrity: AyranIntegrityEnvelope


class GraphQueryResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    query_api_version: SemVer
    query_id: Identifier
    created_at: Timestamp
    stream: GraphStreamIdentity
    query_name: Annotated[
        StrictStr, Field(max_length=128, pattern='^[a-z][a-z0-9_.-]*$')
    ]
    canonical_params: dict[str, Any]
    snapshot: Snapshot
    records: Annotated[list[dict[str, Any]], Field(max_length=100000)]
    truncated: StrictBool
    index_degraded: StrictBool
    query_digest: Hash


class ScopeManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    scope_id: Identifier
    created_at: Timestamp
    run_id: RunId
    revision: Annotated[StrictInt, Field(ge=1, le=9007199254740991)]
    target_identity: TargetIdentity
    included_roots: Annotated[list[RelativePath], Field(max_length=256, min_length=1)]
    excluded_roots: Annotated[list[RelativePath], Field(max_length=256)]
    deployments: Annotated[list[Deployment], Field(max_length=256)]
    chains: Annotated[list[Chain1], Field(max_length=64)]
    fork_blocks: Annotated[list[ForkBlock], Field(max_length=64)]
    rules: Annotated[list[Rule], Field(max_length=256, min_length=1)]
    deny_overrides: Literal[True]
    allowed_hosts: Annotated[list[StrictStr], Field(max_length=64)]
    allowed_endpoints: Annotated[list[Uri], Field(max_length=64)]
    allowed_tools: ReferenceList
    write_roots: Annotated[list[RelativePath], Field(max_length=64, min_length=1)]
    secret_aliases: Annotated[list[SecretAliase], Field(max_length=16)]
    budgets: Budgets
    approval_rules: Annotated[list[ApprovalRule], Field(max_length=8, min_length=8)]
    authorization: Authorization
    valid_from: Timestamp
    valid_until: Timestamp
    provenance: Annotated[
        list[AyranProvenanceRecord], Field(max_length=64, min_length=1)
    ]
    integrity: AyranIntegrityEnvelope


class UntriedDimension_1(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=512, min_length=1)]


class FalsificationAttempt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    result: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
    evidence_ids: ReferenceList
    untried_dimensions: Annotated[list[UntriedDimension_1], Field(max_length=64)]


class CausalChainItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class DissentItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=1024, min_length=1)]


class Schema(RootModel[FindingCandidate | ValidatedFinding]):
    root: Annotated[
        FindingCandidate | ValidatedFinding,
        Field(
            description='Canonical target-bound finding. Only the validated variant contains final gate, causal, scope, impact, dedup, and severity obligations.',
            title='Finding',
        ),
    ]


class Schema_1(RootModel[BatchBegin | BatchEvent | BatchCommit]):
    root: Annotated[
        BatchBegin | BatchEvent | BatchCommit,
        Field(
            description='A line in the frozen Ayran JSONL journal v1 begin/event/commit grammar.',
            title='JournalRecord',
        ),
    ]


class Schema_2(
    RootModel[
        QuarantinedLearningOutcome | EvaluatedLearningOutcome | ReleasedLearningOutcome
    ]
):
    root: Annotated[
        QuarantinedLearningOutcome | EvaluatedLearningOutcome | ReleasedLearningOutcome,
        Field(
            description='Quarantined adjudicated outcome. Released variants require review, tests, held-out evaluation, contamination lineage, rights, and rollback.',
            title='LearningOutcome',
        ),
    ]


class AyranM0ContractRegistry(
    RootModel[
        AyranCommonContractDefinitions
        | AyranWriterAndActorIdentity
        | AyranProvenanceRecord
        | AyranIntegrityEnvelope
        | GraphEvent
        | GraphNode
        | GraphEdge
        | GraphAssertion
        | JournalEvent
        | Schema_1
        | GraphAcknowledgement
        | GraphCheckpoint
        | SegmentManifest
        | GraphIntegrityReport
        | GraphQueryResult
        | CapabilityManifest
        | ScopeManifest
        | Hypothesis
        | EvidenceArtifact
        | ToolRun
        | CoverageCell
        | DAVerdict
        | Schema
        | Schema_2
        | ContextPack
        | RouterAction
    ]
):
    root: Annotated[
        AyranCommonContractDefinitions
        | AyranWriterAndActorIdentity
        | AyranProvenanceRecord
        | AyranIntegrityEnvelope
        | GraphEvent
        | GraphNode
        | GraphEdge
        | GraphAssertion
        | JournalEvent
        | Schema_1
        | GraphAcknowledgement
        | GraphCheckpoint
        | SegmentManifest
        | GraphIntegrityReport
        | GraphQueryResult
        | CapabilityManifest
        | ScopeManifest
        | Hypothesis
        | EvidenceArtifact
        | ToolRun
        | CoverageCell
        | DAVerdict
        | Schema
        | Schema_2
        | ContextPack
        | RouterAction,
        Field(
            description='Offline registry entrypoint for every canonical M0 contract schema.',
            title='Ayran M0 Contract Registry',
        ),
    ]


class Handler(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['model', 'specialist', 'adapter', 'service']
    id: Annotated[StrictStr, Field(pattern='^[a-z][a-z0-9_.-]*$')]
    version: SemVer


class BudgetEffect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_units: Annotated[StrictInt, Field(ge=0, le=10000000)]
    tool_seconds: Annotated[StrictInt, Field(ge=0, le=86400)]
    wall_minutes: Annotated[StrictInt, Field(ge=0, le=1440)]


class Authorization_1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision: Literal['allow', 'deny', 'requires_human_approval']
    scope_manifest_id: Identifier
    rule_ids: ReferenceList
    decided_by: AyranWriterAndActorIdentity
    decided_at: Timestamp
    reason: Annotated[StrictStr, Field(max_length=2048, min_length=1)]
