"""Evidence-pipeline failures with stable machine codes."""

from __future__ import annotations

from typing import Any

from ayran.graph.errors import GraphError

TRANSITION_REJECTED = "TRANSITION_REJECTED"
UNAUTHORIZED_ACTOR = "UNAUTHORIZED_ACTOR"
MISSING_EVIDENCE = "MISSING_EVIDENCE"
EVIDENCE_CEILING = "EVIDENCE_CEILING"
HYPOTHESIS_NOT_FOUND = "HYPOTHESIS_NOT_FOUND"
FINDING_NOT_FOUND = "FINDING_NOT_FOUND"
POC_NOT_FOUND = "POC_NOT_FOUND"
GATE_PRECONDITION = "GATE_PRECONDITION"
REPORT_LINT_FAILED = "REPORT_LINT_FAILED"
# R1 — cognitive inversion (spec §5.1, §5.5, §11.2, §11.4).
VERDICT_OVERRIDE_FORBIDDEN = "VERDICT_OVERRIDE_FORBIDDEN"
WRITER_IMPERSONATION = "WRITER_IMPERSONATION"
ORIGIN_WRITER_DENIED = "ORIGIN_WRITER_DENIED"
REMEMBER_CONTRACT_INVALID = "REMEMBER_CONTRACT_INVALID"
CREDENTIAL_DENIED = "CREDENTIAL_DENIED"
ISOLATION_UNVERIFIED = "ISOLATION_UNVERIFIED"
SUBMISSION_INVALID = "SUBMISSION_INVALID"


class EvidenceError(GraphError):
    """Operator-safe evidence failure; never mutates journal state."""

    def as_result(self) -> dict[str, Any]:
        return {"accepted": False, "error": self.as_dict()}
